config/routes.rb
Rails.application.routes.draw do
  # root path
  root 'html#home'
  
  # event routing
  get '/events/new', to: 'events#new_event', as: :new_event
  post '/events/create', to: 'events#create_event', as: :create_event
  get '/events', to: 'events#show_all_events', as: :show_all_events
  get '/events/:id', to: 'events#show_event', as: :show_event
  get '/events/:id/edit', to: 'events#edit_event', as: :edit_event
  post 'events/:id/update', to: 'events#update_event', as: :update_event
  delete '/events/:id', to: 'events#delete_event', as: :delete_event
  
  # location routing
  get '/locations/new', to: 'locations#new_location', as: :new_location
  post '/locations/create', to: 'locations#create_location', as: :create_location
  get '/locations', to: 'locations#show_all_locations', as: :show_all_locations
  get '/locations/:id', to: 'locations#show_location', as: :show_location
  get '/locations/:id/edit', to: 'locations#edit_location', as: :edit_location
  post 'locations/:id/update', to: 'locations#update_location', as: :update_location
  delete '/locations/:id', to: 'locations#delete_location', as: :delete_location
  
  # user routing
  get '/users/new', to: 'users#new_user', as: :new_user
  post '/users/create', to: 'users#create_user', as: :create_user
  get '/users', to: 'users#show_all_users', as: :show_all_users
  get '/users/:id', to: 'users#show_user', as: :show_user
  get '/users/:id/edit', to: 'users#edit_user', as: :edit_user
  post 'users/:id/update', to: 'users#update_user', as: :update_user
  delete '/users/:id', to: 'users#delete_user', as: :delete_user
  
  # visit routing
  get '/:tag', to: 'visits#new_visit', as: :new_visit
  post '/:tag', to: 'visits#create_visit', as: :create_visit
end

app/models/event.rb
class Event < ActiveRecord::Base
    # location associations
    has_and_belongs_to_many :locations
    
    # user associations
    has_many :participates
    has_many :participants, through: :participates, source: 'user'
    belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
end

app/models/location.rb
class Location < ActiveRecord::Base
    # event associations
    has_and_belongs_to_many :events
    
    # user associations
    has_many :visits
    has_many :visitors, through: :visits, source: 'user'
    belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
end

app/models/participate.rb
class Participate < ActiveRecord::Base
    belongs_to :event
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    # event associations
    has_many :participates
    has_many :participating_events, through: :participates, source: 'event'
    has_many :owned_events, class_name: 'Event'
    
    # location associations
    has_many :visits
    has_many :visited_locations, through: :visits, source: 'location'
    has_many :owned_locations, class_name: 'Location'
end

app/models/visit.rb
class Visit < ActiveRecord::Base
    belongs_to :location
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    # GET /events/new
    def new_event
    end
    
    # POST /events/create
    def create_event
        @event = Event.new(
            name: params[:name],
            description: params[:description],
            start_date: params[:start_date],
            end_date: params[:end_date]
        )
        
        if @event.save
            redirect_to show_event_path(@event)
        else
            redirect_to root_path
        end
    end
    
    # GET /events
    def show_all_events
        @events = Event.all
    end
    
    # GET /events/:id
    def show_event
        @event = Event.find(params[:id])
    end
    
    # GET /events/:id/edit
    def edit_event
        @event = Event.find(params[:id])
    end
    
    # POST /events/update
    def update_event
        @event = Event.find(params[:id])
        
        if @event.update(
                name: params[:event][:name],
                description: params[:event][:description],
                start_date: params[:event][:start_date],
                end_date: params[:event][:end_date]
            )
            redirect_to show_event_path(@event)
        else
            redirect_to root_path
        end
    end
    
    # DELETE /events/:id
    def delete_event
        @event = Event.find(params[:id])
        
        if @event.destroy
            redirect_to show_all_events_path
        else
            redirect_to show_event_path(@event)
        end
    end
end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
    # GET /
    def home
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    # GET /locations/new
    def new_location
    end
    
    # POST /locations/create
    def create_location
        @location = Location.new(
            name: params[:name],
            description: params[:description],
            tag: (('A'..'Z').to_a + ('a'..'z').to_a + (0..9).to_a).shuffle[0..7].join,
            coordinates: params[:coordinates]
        )
        
        if @location.save
            redirect_to show_location_path(@location)
        else
            redirect_to root_path
        end
    end
    
    # GET /locations
    def show_all_locations
        @locations = Location.all
    end
    
    # GET /locations/:id
    def show_location
        @location = Location.find(params[:id])
        @qr=RQRCode::QRCode.new("#{root_url}#{@location.tag}", size: 8)
    end
    
    # GET /locations/:id/edit
    def edit_location
        @location = Location.find(params[:id])
    end
    
    # POST /locations/:id/update
    def update_location
        @location = Location.find(params[:id])
        
        if @location.update(
                name: params[:location][:name],
                description: params[:location][:description],
                coordinates: params[:location][:coordinates]
            )
            redirect_to show_location_path(@location)
        else
            redirect_to root_path
        end
    end
    
    # DELETE /locations/:id
    def delete_location
        @location = Location.find(params[:id])
        
        if @location.destroy
            redirect_to show_all_locations_path
        else
            redirect_to show_location_path(@location)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # GET /users/new
    def new_user
    end
    
    # POST /users/create
    def create_user
        @user = User.new(
            first_name: params[:first_name],
            last_name: params[:last_name],
            email: params[:email]
        )
        
        if @user.save
            redirect_to show_user_path(@user)
        else
            redirect_to root_path
        end
    end
    
    # GET /users
    def show_all_users
        @users = User.all
    end
    
    # GET /users/:id
    def show_user
        @user = User.find(params[:id])
    end
    
    # GET /users/:id/edit
    def edit_user
        @user = User.find(params[:id])
    end
    
    # POST /users/:id/update
    def update_user
        @user = User.find(params[:id])
        
        if @user.update(
                first_name: params[:user][:first_name],
                last_name: params[:user][:last_name],
                email: params[:user][:email]
            )
            redirect_to show_user_path(@user)
        else
            redirect_to root_path
        end
    end
    
    # DELETE /users/:id
    def delete_user
        @user = User.find(params[:id])
        
        if @user.destroy
            redirect_to show_all_users_path
        else
            redirect_to show_user_path(@user)
        end
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
    # GET /:tag
    def new_visit
        @location = Location.find_by(tag: params[:tag])
    end
    
    # POST /:tag
    def create_visit
    	@user = User.find_by(email: params[:email])
    	@location = Location.find_by(tag: params[:tag])		
    	@user.visited_locations << @location
        redirect_to show_user_path(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit_event.html.erb
<%= form_for @event, url: update_event_path, method: 'post' do |f| %>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :description, 'Description' %>
    <%= f.text_field :description %>
    <br>
    <%= f.label :start_date, 'Starts on' %>
    <%= f.text_field :start_date %>
    <br>
    <%= f.label :end_date, 'Ends on' %>
    <%= f.text_field :end_date %>
    <br>
    <%= f.submit 'Update' %>
<% end%>

app/views/events/new_event.html.erb
<%= form_tag(create_event_path, method: 'post') do %>
    <%= label_tag(:name, 'Name') %>
    <%= text_field_tag(:name) %>
    <br>
    <%= label_tag(:description, 'Description') %>
    <%= text_field_tag(:description) %>
    <br>
    <%= label_tag(:start_date, 'Starts on') %>
    <%= text_field_tag(:start_date) %>
    <br>
    <%= label_tag(:end_date, 'Ends on') %>
    <%= text_field_tag(:end_date) %>
    <br>
    <%= submit_tag('Submit') %>
<% end%>

app/views/events/show_all_events.html.erb
<table>
    <tr>
        <th>Event</th>
        <th>Start</th>
        <th>End</th>
    </tr>
    
    <% @events.each do |event| %>
        <tr>
            <td><%= event.name %></td>
            <td><%= event.start_date %></td>
            <td><%= event.end_date %></td>
            <td><%= link_to 'show', show_event_path(event) %></td>
            <td><%= link_to 'edit', edit_event_path(event) %></td>
            <td><%= link_to 'delete', delete_event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
    <% end %>
</table>

<p><%= link_to 'Create New Event', new_event_path %></p>

app/views/events/show_event.html.erb
<h2><%= @event.name %></h2>
<p><%= @event.description %></p>
<p><b>start: </b><%= @event.start_date %></p>
<p><b>end: </b></b><%= @event.end_date %></p>

<h3>Locations</h3>

<table>
    <tr>
        <th>Location</th>
        <th>Description</th>
    </tr>
    
    <% @event.locations.each do |loc| %>
        <tr>
            <td><%= loc.name %></td>
            <td><%= loc.description %></td>
        </tr>
    <% end %>
</table>

<h3>Participants</h3>

<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    
    <% @event.participants.each do |u| %>
        <tr>
            <td><%= "#{u.first_name} #{u.last_name}" %></td>
            <td><%= u.email %></td>
        </tr>
    <% end %>
</table>

app/views/html/home.html.erb
<p><%= link_to 'Events', show_all_events_path %></p>
<p><%= link_to 'Locations', show_all_locations_path %></p>
<p><%= link_to 'Users', show_all_users_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScavengerHunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/edit_location.html.erb
<%= form_for @location, url: update_location_path, method: 'post' do |f| %>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :description, 'Description' %>
    <%= f.text_field :description %>
    <br>
    <%= f.label :coordinates, 'Coordinates' %>
    <%= f.text_field :coordinates %>
    <br>
    <%= f.submit 'Submit' %>
<% end%>

app/views/locations/new_location.html.erb
<%= form_tag(create_location_path, method: 'post') do %>
    <%= label_tag(:name, 'Name') %>
    <%= text_field_tag(:name) %>
    <br>
    <%= label_tag(:description, 'Description') %>
    <%= text_field_tag(:description) %>
    <br>
    <%= label_tag(:coordinates, 'Coordinates') %>
    <%= text_field_tag(:coordinates) %>
    <br>
    <%= submit_tag('Submit') %>
<% end%>

app/views/locations/show_all_locations.html.erb
<table>
    <tr>
        <th>Location</th>
    </tr>
    
    <% @locations.each do |location| %>
        <tr>
            <td><%= location.name %></td>
            <td><%= link_to 'show', show_location_path(location) %></td>
            <td><%= link_to 'edit', edit_location_path(location) %></td>
            <td><%= link_to 'delete', delete_location_path(location), method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
    <% end %>
</table>

<p><%= link_to 'Create New Location', new_location_path %></p>

app/views/locations/show_location.html.erb
<h2><%= @location.name %></h2>
<p><%= @location.description %></p>
<br>
<%= raw @qr.as_html %>

app/views/users/edit_user.html.erb
<%= form_for @user, url: update_user_path, method: 'post' do |f| %>
    <%= f.label :first_name, 'First Name' %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name, 'Last Name' %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
    <br>
    <%= f.submit 'Submit' %>
<% end%>

app/views/users/new_user.html.erb
<%= form_tag(create_user_path, method: 'post') do %>
    <%= label_tag(:first_name, 'First Name') %>
    <%= text_field_tag(:first_name) %>
    <br>
    <%= label_tag(:last_name, 'Last Name') %>
    <%= text_field_tag(:last_name) %>
    <br>
    <%= label_tag(:email, 'Email') %>
    <%= text_field_tag(:email) %>
    <br>
    <%= submit_tag('Submit') %>
<% end%>

app/views/users/show_all_users.html.erb
<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    
    <% @users.each do |user| %>
        <tr>
            <td><%= "#{user.first_name} #{user.last_name}" %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'show', show_user_path(user) %></td>
            <td><%= link_to 'edit', edit_user_path(user) %></td>
            <td><%= link_to 'delete', delete_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>

<p><%= link_to 'Create New User', new_user_path %></p>

app/views/users/show_user.html.erb
<h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
<p><%= @user.email %></p>

<h3>Events</h3>

<table>
    <tr>
        <th>Owned Event</th>
    </tr>
    
    <% @user.owned_events.each do |event| %>
        <tr>
            <td><%= event.name %></td>
        </tr>
    <% end %>
    
    <tr>
        <th>Participated Event</th>
    </tr>
    
    <% @user.participating_events.each do |event| %>
        <tr>
            <td><%= event.name %></td>
            <td> 
                <table>
                    <tr>
                        <th>Location</th>
                        <th>Visited?</th>
                    </tr>
                    <% event.locations.each do |i| %>
                        <tr>
                            <td><%= location.name %></td>
                            <td>
                                <% if @user.visited_locations.include? location %>
                                    Y
                                <% else %>
                                    N
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </table>
            </td>
        </tr>
    <% end %>
</table>

<h3>Owned Locations</h3>

<table>
    <tr>
        <th>Name</th>
    </tr>
    
    <% @user.owned_locations.each do |location| %>
        <tr>
            <td><%= location.name %></td>
        </tr>
    <% end %>
</table>

app/views/visits/new_visit.html.erb
<%= form_tag(create_visit_path, method: 'post') do %> 
    <%= label_tag(:email, 'E-mail') %>
    <%= text_field_tag(:email) %>
    <%= hidden_field_tag('tag', @location.tag) %>
<% end %>